# Generated by Django 3.2.4 on 2021-08-23 13:08

from django.db import migrations, models
import felix.storages


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='logo',
            field=models.ImageField(storage=felix.storages.PublicAzureStorage(), upload_to='insurer-logos'),
        ),
    ]
