# Generated by Django 3.2.4 on 2021-08-23 13:08

from django.db import migrations, models
import felix.storages


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, storage=felix.storages.PublicAzureStorage(), upload_to='company-logos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, storage=felix.storages.PublicAzureStorage(), upload_to='user-profile-images'),
        ),
    ]
