# Generated by Django 3.2.4 on 2021-08-24 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210823_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='allowed_workspaces',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MT', 'Motor'), ('MG', 'Mortgage')], max_length=2), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_workspaces',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MT', 'Motor'), ('MG', 'Mortgage')], max_length=2), blank=True, default=list, help_text='Comma separated list of values from: MT, MG', size=None),
        ),
    ]
