# Generated by Django 3.1.1 on 2021-04-29 09:29

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorinsurance_shared.carmake')),
            ],
            options={
                'ordering': ['make', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='product-logos')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=500)),
                ('is_tpl_product', models.BooleanField(default=False)),
                ('allows_agency_repair', models.BooleanField(default=True)),
                ('repair_type_description_non_agency', models.CharField(blank=True, default='', max_length=500)),
                ('document_url', models.URLField(blank=True, max_length=250)),
                ('rent_a_car', models.JSONField(help_text='Rent a car')),
                ('road_side_assistance', models.JSONField(help_text='Road side assistance')),
                ('pab_driver', models.JSONField(help_text='PAB driver')),
                ('pab_passenger', models.JSONField(help_text='PAB passenger')),
                ('pab_family_and_friends', models.JSONField(help_text='PAB family and friends')),
                ('fire_and_theft_cover', models.JSONField(help_text='Fire and theft cover')),
                ('natural_disaster', models.JSONField(help_text='Natural disaster')),
                ('riot_and_strike', models.JSONField(help_text='Riot and strike')),
                ('windscreen_and_glass_damage', models.JSONField(help_text='Windscreen and glass damage')),
                ('emergency_medical_expenses', models.JSONField(help_text='Emergency medical expenses')),
                ('personal_belongings', models.JSONField(help_text='Personal belongings')),
                ('replacement_keys_and_locks', models.JSONField(help_text='Replacement keys and locks')),
                ('oman_cover', models.JSONField(help_text='Oman cover')),
                ('off_road_cover', models.JSONField(help_text='Off-road cover')),
                ('ambulance_cover', models.JSONField(help_text='Ambulance cover')),
                ('third_party_property_damage', models.JSONField(help_text='Third party property damage')),
                ('third_party_bodily_injury', models.JSONField(help_text='third party bodily injury')),
                ('can_auto_quote', models.BooleanField(default=False)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurers.insurer')),
            ],
            options={
                'ordering': ['-created_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[('2021', 2021), ('2020', 2020), ('2019', 2019), ('2018', 2018), ('2017', 2017), ('2016', 2016), ('2015', 2015), ('2014', 2014), ('2013', 2013), ('2012', 2012), ('2011', 2011), ('2010', 2010), ('2009', 2009), ('2008', 2008), ('2007', 2007), ('2006', 2006), ('2005', 2005), ('2004', 2004), ('2003', 2003), ('2002', 2002), ('2001', 2001), ('2000', 2000), ('1999', 1999), ('1998', 1998), ('1997', 1997), ('1996', 1996), ('1995', 1995), ('1994', 1994)])),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('algo_driven_id', models.CharField(blank=True, default='', max_length=30)),
                ('algo_driven_data', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorinsurance_shared.carmodel')),
            ],
            options={
                'ordering': ['year', 'model__make', 'model', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AutoQuoterCarTrimData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(choices=[('oic', 'Oman Insurance Company'), ('qic', 'Qatar Insurance Company'), ('uic', 'Union Insurance Company'), ('new india', 'New India Insurance'), ('insurance house', 'Insurance House'), ('tokio marine', 'Tokio Marine'), ('tokio marine api', 'Tokio Marine API'), ('aman', 'Aman'), ('aman api', 'Aman API'), ('arabia', 'Arabia'), ('dnirc', 'DNIRC'), ('al ittihad al watani insurace', 'Al Ittihad Al Watani Insurance'), ('watania', 'Watania Insurance'), ('al ain ahlia', 'Al Ain Ahlia Insurance Company'), ('al sagr', 'Al Sagr Insurance')], editable=False, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('trim', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='motorinsurance_shared.cartrim')),
            ],
        ),
    ]
