country_mapping = {
    'AF': 'AFGHANISTAN',
    'AX': 'Aland Islands',
    'AL': 'ALBANIA',
    'DZ': 'ALGERIA',
    'AS': 'AMERICAN SAMOA',
    'AD': 'ANDORRA',
    'AO': 'ANGOLA',
    'AI': 'ANGUILLA',
    'AQ': 'ANTARCTICA',
    'AG': 'ANTIGUA AND BARBUDA',
    'AR': 'ARGENTINA',
    'AM': 'ARMENIA',
    'AW': 'ARUBA',
    'AU': 'AUSTRALIA',
    'AT': 'AUSTRIA',
    'AZ': 'AZERBAIJAN',
    'BS': 'BAHAMAS',
    'BH': 'BAHRAIN',
    'BD': 'BANGLADESH',
    'BB': 'BARBADOS',
    'BY': 'BELARUS',
    'BE': 'BELGIUM',
    'BZ': 'BELIZE',
    'BJ': 'BENIN',
    'BM': 'BERMUDA',
    'BT': 'BHUTAN',
    'BO': 'BOLIVIA',
    'BA': 'BOSNIA AND HERZEGOWINA',
    'BW': 'BOTSWANA',
    'BV': 'BOUVET ISLAND',
    'BR': 'BRAZIL',
    'IO': 'BRITISH INDIAN OCEAN TERRITORY',
    'BN': 'BRUNEI DARUSSALAM',
    'BG': 'BULGARIA',
    'BF': 'BURKINA FASO',
    'BI': 'BURUNDI',
    'KH': 'CAMBODIA',
    'CM': 'CAMEROON',
    'CA': 'CANADA',
    'ES': 'SPAIN',
    'CV': 'CAPE VERDE',
    'KY': 'CAYMAN ISLANDS',
    'CF': 'CENTRAL AFRICAN REPUBLIC',
    'TD': 'CHAD',
    'CL': 'CHILE',
    'CN': 'CHINA',
    'CX': 'CHRISTMAS ISLAND',
    'CC': 'COCOS (KEELING) ISLANDS',
    'CO': 'COLOMBIA',
    'KM': 'COMOROS',
    'CD': 'ZAIRE',
    'CG': 'Congo (Brazzaville)',
    'CK': 'COOK ISLANDS',
    'CR': 'COSTA RICA',
    'CI': 'IVORY COAST',
    'HR': 'CROATIA',
    'CU': 'CUBA',
    'CY': 'CYPRUS',
    'CZ': 'CZECH REPUBLIC',
    'DK': 'DENMARK',
    'DJ': 'DJIBOUTI',
    'DM': 'DOMINICA',
    'DO': 'DOMINICAN REPUBLIC',
    'TL': 'Timor-Leste',
    'EC': 'ECUADOR',
    'EG': 'EGYPT',
    'SV': 'EL SALVADOR',
    'GQ': 'EQUATORIAL GUINEA',
    'ER': 'ERITREA',
    'EE': 'ESTONIA',
    'ET': 'ETHIOPIA',
    'FK': 'FALKLAND ISLANDS (MALVINAS)',
    'FO': 'FAROE ISLANDS',
    'FJ': 'FIJI',
    'FI': 'FINLAND',
    'FR': 'FRANCE, METROPOLITAN',
    'GF': 'FRENCH GUIANA',
    'PF': 'FRENCH POLYNESIA',
    'TF': 'FRENCH SOUTHERN TERRITORIES',
    'GA': 'GABON',
    'GM': 'GAMBIA',
    'GE': 'GEORGIA',
    'DE': 'GERMANY',
    'GH': 'GHANA',
    'GI': 'GIBRALTAR',
    'GR': 'GREECE',
    'GL': 'GREENLAND',
    'GD': 'GRENADA',
    'GP': 'GUADELOUPE',
    'GU': 'GUAM',
    'GT': 'GUATEMALA',
    'GG': 'Guernsey',
    'GN': 'GUINEA',
    'GW': 'GUINEA-BISSAU',
    'GY': 'GUYANA',
    'HT': 'HAITI',
    'HM': 'HEARD AND MC DONALD ISLANDS',
    'HN': 'HONDURAS',
    'HK': 'HONGKONG',
    'HU': 'HUNGARY',
    'IS': 'ICELAND',
    'IN': 'INDIA',
    'ID': 'INDONESIA',
    'IR': 'IRAN',
    'IQ': 'IRAQ',
    'IE': 'IRELAND',
    'IM': 'Isle of Man',
    'IT': 'ITALY',
    'JM': 'JAMAICA',
    'JP': 'JAPAN',
    'JE': 'Jersey',
    'JO': 'JORDAN',
    'KZ': 'KAZAKHSTAN',
    'KE': 'KENYA',
    'KI': 'KIRIBATI',
    'KP': "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    'KR': 'KOREA, REPUBLIC OF',
    'KW': 'KUWAIT',
    'KG': 'KYRGYZSTAN',
    'LA': "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    'LV': 'LATVIA',
    'LB': 'LEBANON',
    'LS': 'LESOTHO',
    'LR': 'LIBERIA',
    'LY': 'LIBYAN ARAB JAMAHIRIYA',
    'LI': 'LIECHTENSTEIN',
    'LT': 'LITHUANIA',
    'LU': 'LUXEMBOURG',
    'MO': 'MACAU',
    'MK': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
    'MG': 'MADAGASCAR',
    'MW': 'MALAWI',
    'MY': 'MALAYSIA',
    'MV': 'MALDIVES',
    'ML': 'MALI',
    'MT': 'MALTA',
    'MH': 'MARSHALL ISLANDS',
    'MQ': 'MARTINIQUE',
    'MR': 'MAURITANIA',
    'MU': 'MAURITIUS',
    'YT': 'MAYOTTE',
    'MX': 'MEXICO',
    'FM': 'MICRONESIA, FEDERATED STATES OF',
    'MD': 'MOLDOVA, REPUBLIC OF',
    'MC': 'MONACO',
    'MN': 'MONGOLIA',
    'ME': 'Montenegro',
    'MS': 'MONTSERRAT',
    'MA': 'MOROCCO',
    'MZ': 'MOZAMBIQUE',
    'MM': 'MYANMAR',
    'NA': 'NAMIBIA',
    'NR': 'NAURU',
    'NP': 'NEPAL',
    'NL': 'NETHERLANDS ANTILLES',
    'NC': 'NEW CALEDONIA',
    'NZ': 'NEW ZEALAND',
    'NI': 'NICARAGUA',
    'NE': 'NIGER',
    'NG': 'NIGERIA',
    'NU': 'NIUE',
    'NF': 'NORFOLK ISLAND',
    'MP': 'NORTHERN MARIANA ISLANDS',
    'NO': 'NORWAY',
    'OM': 'OMAN',
    'PK': 'PAKISTAN',
    'PW': 'PALAU',
    'PS': 'Palestinian Territory, Occupied',
    'PA': 'PANAMA',
    'PG': 'PAPUA NEW GUINEA',
    'PY': 'PARAGUAY',
    'PE': 'PERU',
    'PH': 'PHILIPPINES',
    'PN': 'PITCAIRN',
    'PL': 'POLAND',
    'PT': 'PORTUGAL',
    'PR': 'PUERTO RICO',
    'QA': 'QATAR',
    'RO': 'ROMANIA',
    'RU': 'RUSSIAN FEDERATION',
    'RW': 'RWANDA',
    'SH': 'ST. HELENA',
    'KN': 'SAINT KITTS AND NEVIS',
    'LC': 'SAINT LUCIA',
    'PM': 'ST. PIERRE AND MIQUELON',
    'VC': 'SAINT VINCENT AND THE GRENADINES',
    'BL': 'Saint-Barthélemy',
    'MF': 'Saint-Martin (French part)',
    'WS': 'SAMOA',
    'SM': 'SAN MARINO',
    'ST': 'SAO TOME AND PRINCIPE',
    'SA': 'SAUDI ARABIA',
    'SN': 'SENEGAL',
    'RS': 'SERBIA',
    'SC': 'SEYCHELLES',
    'SL': 'SIERRA LEONE',
    'SG': 'SINGAPORE',
    'SK': 'SLOVAKIA (SLOVAK REPUBLIC)',
    'SI': 'SLOVENIA',
    'SB': 'SOLOMON ISLANDS',
    'SO': 'SOMALIA',
    'ZA': 'SOUTH AFRICA',
    'GS': 'South Georgia and the South Sandwich Islands',
    'SS': 'South Sudan',
    'LK': 'SRI LANKA',
    'SD': 'SUDAN',
    'SR': 'SURINAME',
    'SJ': 'SVALBARD AND JAN MAYEN ISLANDS',
    'SZ': 'SWAZILAND',
    'SE': 'SWEDEN',
    'CH': 'SWITZERLAND',
    'SY': 'Syrian Arab Republic (Syria)',
    'TW': 'Taiwan, Republic of China',
    'TJ': 'TAJIKISTAN',
    'TZ': 'TANZANIA, UNITED REPUBLIC OF',
    'TH': 'THAILAND',
    'TG': 'TOGO',
    'TK': 'TOKELAU',
    'TO': 'TONGA',
    'TT': 'TRINIDAD AND TOBAGO',
    'TN': 'TUNISIA',
    'TR': 'TURKEY',
    'TM': 'TURKMENISTAN',
    'TC': 'TURKS AND CAICOS ISLANDS',
    'TV': 'TUVALU',
    'GB': 'UNITED KINGDOM',
    'UG': 'UGANDA',
    'UA': 'UKRAINE',
    'AE': 'UNITED ARAB EMIRATES',
    'UM': 'UNITED STATES MINOR OUTLYING ISLANDS',
    'UY': 'URUGUAY',
    'US': 'USA',
    'UZ': 'UZBEKISTAN',
    'VU': 'VANUATU',
    'VA': 'VATICAN CITY STATE (HOLY SEE)',
    'VE': 'Venezuela (Bolivarian Republic of)',
    'VN': 'VIET NAM',
    'VG': 'VIRGIN ISLANDS (BRITISH)',
    'VI': 'Virgin Islands, US',
    'WF': 'WALLIS AND FUTUNA ISLANDS',
    'EH': 'WESTERN SAHARA',
    'YE': 'YEMEN',
    'ZM': 'ZAMBIA',
    'ZW': 'ZIMBABWE',
    'RE': 'REUNION',
}

driving_experience = {
    "less than 6 months": "0 to 6 Months",
    "less than 1 year": "6 to 12 Months",
    "less than 2 years": "Above 12 Months",
    "more than 2 years": "Above 12 Months",
}

emirates = {
    "DU": "DUBAI",
    "AD": "ABU DHABI",
    "SJ": "SHARJAH",
    "AJ": "AJMAN",
    "RK": "RAK",
    "FJ": "FUJAIRAH",
    "UQ": "Umm Al Quwain",
}

car_makes = {
    'Haval': 'HAVAL',
    'Changan': 'CHANGAN',
    'Honda': 'HONDA',
    'Alfa Romeo': 'ALFA ROMEO',
    'Great Wall': 'GREAT WALL',
    'Renault': 'RENAULT',
    'Maserati': 'MASERATI',
    'BMW': 'BMW',
    'Saab': 'SAAB',
    'Porsche': 'PORSCHE',
    'Daihatsu': 'DAIHATSU',
    'GMC': 'GMC',
    'Mazda': 'MAZDA',
    'Toyota': 'TOYOTA',
    'McLaren': 'MCLAREN',
    'SEAT': 'SEAT',
    'Cadillac': 'CADILLAC',
    'Lamborghini': 'LAMBORGHINI',
    'Chevrolet': 'CHEVROLET',
    'MG': 'MG',
    'Luxgen': 'LUXGEN',
    'Ssangyong': 'SSANGYONG',
    'Maybach': 'MAYBACH',
    'Peugeot': 'PEUGEOT',
    'Suzuki': 'SUZUKI',
    'Chery': 'CHERY',
    'Jeep': 'JEEP',
    'Brilliance': 'BRILLIANCE',
    'Lincoln': 'LINCOLN',
    'Kia': 'KIA',
    'Bugatti': 'BUGATTI',
    'Opel': 'OPEL',
    'Mitsubishi': 'MITSUBISHI',
    'Lexus': 'LEXUS',
    'Ferrari': 'FERRARI',
    'Hummer': 'HUMMER',
    'Infiniti': 'INFINITI',
    'Volkswagen': 'VOLKSWAGEN',
    'Aston Martin': 'ASTON MARTIN',
    'Bentley': 'BENTLEY',
    'Fisker': 'FISKER',
    'RAM': 'RAM',
    'Nissan': 'NISSAN',
    'Audi': 'AUDI',
    'Land Rover': 'LAND ROVER',
    'Chrysler': 'CHRYSLER',
    'Subaru': 'SUBARU',
    'MINI': 'MINI',
    'Geely': 'GEELY',
    'Fiat': 'FIAT',
    'Ford': 'FORD',
    'Jaguar': 'JAGUAR',
    'Lotus': 'LOTUS',
    'Volvo': 'VOLVO',
    'Dodge': 'DODGE',
    'JAC': 'JAC',
    'Proton': 'PROTON',
    'Mercury': 'MERCURY',
    'Hyundai': 'HYUNDAI',
    'Citroën': 'CITROEN',
    'Mercedes-Benz': 'MERCEDES BENZ',
    'Škoda': 'SKODA',
    'Rolls-Royce': 'ROLLS ROYCE'
}
