# Generated by Django 3.2.4 on 2021-08-24 11:40

import core.mixins
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mortgage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('accounts', '0002_auto_20210823_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('property_valuation_fee', models.IntegerField()),
                ('bank_processing_fee_rate', models.FloatField(blank=True, null=True)),
                ('bank_processing_fee_extra', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_bank_processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('life_insurance_monthly_rate', models.FloatField(help_text='In percentage')),
                ('property_insurance_yearly_rate', models.FloatField(help_text='Property Insurance Yearly in percentage')),
                ('full_settlement_percentage', models.FloatField(default=0)),
                ('full_settlement_max_value', models.FloatField(default=0)),
                ('free_partial_payment_per_year', models.FloatField(default=0)),
                ('add_fees_to_loan_amount', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='BankInterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True)),
                ('interest_rate', models.FloatField(default=0)),
                ('interest_rate_addition', models.FloatField(blank=True, null=True)),
                ('introduction_period_in_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_introduction_rate', models.FloatField(blank=True, null=True)),
                ('post_introduction_rate_addition', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('serial_number', models.PositiveIntegerField(editable=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_interest_rates', to='mortgage.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('new', 'New Deal'), ('quote', 'Quote Sent'), ('pre approval', 'Pre Approval'), ('valuation', 'Valuation'), ('final offer', 'Final Offer'), ('settlement', 'Settlement'), ('loan disbursal', 'Loan Disbursal'), ('property transfer', 'Property Transfer'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], default='new', max_length=50)),
                ('deal_type', models.CharField(choices=[('new', 'New'), ('duplicate', 'Duplicate'), ('renewal', 'Renewal'), ('developer', 'Developer'), ('buy out', 'Buy Out'), ('refinance', 'Re-finance'), ('resale', 'Resale')], default='new', max_length=50)),
                ('quote_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('waiting for client', 'Waiting for client'), ('waiting for us', 'Waiting for us'), ('waiting for bank', 'Waiting for bank')], default='active', max_length=50)),
                ('property_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('expat', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50)),
                ('tenure', models.IntegerField()),
                ('l_tv', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_customer', to='customers.customer')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_owner', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(core.mixins.AuditTrailMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('note', models.CharField(max_length=1000)),
                ('reference_number', models.CharField(default=mortgage.models.reference_number, max_length=50)),
                ('number_of_view', models.IntegerField()),
                ('is_segmented', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('bank', models.ManyToManyField(related_name='mortgage_bank_quotes', to='mortgage.Bank')),
                ('deals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_quote_deals', to='mortgage.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostApproval',
            fields=[
                ('approval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.approval')),
            ],
            bases=('mortgage.approval',),
        ),
        migrations.CreateModel(
            name='PreApproval',
            fields=[
                ('approval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mortgage.approval')),
            ],
            bases=('mortgage.approval',),
        ),
        migrations.CreateModel(
            name='SegmentedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_segmented_bank', to='mortgage.bank')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_segmented_quote', to='mortgage.quote')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_segmented_rate', to='mortgage.bankinterestrate')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=250)),
                ('invoice_number', models.CharField(blank=True, max_length=250)),
                ('policy_document', models.FileField(max_length=250, upload_to='')),
                ('invoice_document', models.FileField(blank=True, max_length=250, upload_to='')),
                ('policy_start_date', models.DateField(blank=True)),
                ('policy_expiry_date', models.DateField(blank=True)),
                ('disbursement_date', models.DateField(blank=True)),
                ('custom_product_name', models.CharField(blank=True, max_length=250)),
                ('insurance_type', models.CharField(blank=True, choices=[('comprehensive', 'Comprehensive'), ('tpl', 'Third Party Liability (TPL)')], max_length=250)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductible_extras', models.TextField(blank=True)),
                ('mortgage_by', models.CharField(blank=True, max_length=250)),
                ('default_add_ons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=250, null=True), size=None)),
                ('paid_add_ons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=250, null=True), size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_policy', to='mortgage.bank')),
                ('deals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_policy', to='mortgage.deal')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_policy_referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=100)),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_by_agent', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_void', models.BooleanField(default=False)),
                ('mortgage_by', models.CharField(blank=True, default='', max_length=250)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('policy_start_date', models.DateField(blank=True)),
                ('selected_add_ons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=250), size=None)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_bank', to='mortgage.deal')),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bank', to='mortgage.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('load_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('extra_financing', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('expat', models.CharField(max_length=45)),
                ('tenure', models.CharField(max_length=45)),
                ('l_tv', models.CharField(max_length=45)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('deals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_leads_deal', to='mortgage.deal')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_lead_user', to='accounts.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_lead_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_mortgage_profiles', to='customers.customer')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_quote_approvals', to='mortgage.deal'),
        ),
    ]
