# Generated by Django 3.2.4 on 2021-09-04 15:29

from django.db import migrations, models
import django.db.models.deletion
import mortgage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_alter_deal_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eibar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eibar_rate', models.FloatField(help_text='Value must be in percentage')),
                ('eibar_duration', models.PositiveIntegerField(help_text='Duration of the Eibar')),
            ],
            bases=(mortgage.models.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GovernmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustee_center_fee', models.FloatField(help_text='Do not include the vat here')),
                ('property_fee_rate', models.FloatField(help_text='Land department property registration fee in percentage')),
                ('property_fee_addition', models.FloatField(help_text='Land department property registration fixed fee in numbers')),
                ('mortgage_fee_rate', models.FloatField(help_text='Land department property registration fee in percentage')),
                ('mortgage_fee_addition', models.FloatField(help_text='Land department property registration fixed fee in numbers')),
                ('real_state_fee', models.FloatField(help_text='Real state fee in percentage excluding vat')),
            ],
            bases=(mortgage.models.SingleInstanceMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mortgage',
            new_name='bank',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_add_ons',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=mortgage.models.order_number, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_processing_fee_rate',
            field=models.FloatField(blank=True, help_text='Value must be in percentage', null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='life_insurance_monthly_rate',
            field=models.FloatField(help_text='Value must be in percentage'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='property_insurance_yearly_rate',
            field=models.FloatField(help_text='Value must be in percentage'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('new', 'New Deal'), ('quote', 'Quote Sent'), ('preApproval', 'Pre Approval'), ('valuation', 'Valuation'), ('offer', 'Final Offer'), ('settlement', 'Settlement'), ('loanDisbursal', 'Loan Disbursal'), ('propertyTransfer', 'Property Transfer'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_bank', to='mortgage.deal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number_of_view',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
