# Generated by Django 3.2.4 on 2021-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0003_auto_20210904_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinterestrate',
            name='interest_rate_addition',
        ),
        migrations.RemoveField(
            model_name='bankinterestrate',
            name='post_introduction_rate_addition',
        ),
        migrations.AddField(
            model_name='bankinterestrate',
            name='eibar_duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration of the Eibar in months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankinterestrate',
            name='eibar_rate',
            field=models.FloatField(default=1, help_text='Value must be in percentage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eibar',
            name='eibar_duration',
            field=models.PositiveIntegerField(help_text='Duration of the Eibar in months'),
        ),
    ]
