# Generated by Django 3.2.4 on 2021-09-10 22:04

from django.db import migrations, models
import mortgage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0004_auto_20210909_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eibor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eibor_rate', models.FloatField(help_text='Value must be in percentage')),
            ],
            bases=(mortgage.models.SingleInstanceMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Eibar',
        ),
        migrations.RenameField(
            model_name='bankinterestrate',
            old_name='eibar_rate',
            new_name='eibor_rate',
        ),
        migrations.RemoveField(
            model_name='bankinterestrate',
            name='eibar_duration',
        ),
    ]
