# Generated by Django 3.2.4 on 2021-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_auto_20210911_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
