# Generated by Django 3.2.4 on 2021-09-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0006_auto_20210911_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinterestrate',
            name='eibor_duration',
            field=models.FloatField(default=1, help_text='Eibor Months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankinterestrate',
            name='introduction_period_in_years',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
