# Generated by Django 3.2.4 on 2021-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0007_auto_20210912_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='down_payment',
            field=models.IntegerField(default=0),
        ),
    ]
