# Generated by Django 3.2.4 on 2021-09-12 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0008_alter_deal_down_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='processed_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('active', 'Active'), ('deleted', 'Deleted'), ('waiting for client', 'Waiting for client'), ('waiting for us', 'Waiting for us'), ('waiting for bank', 'Waiting for bank')], max_length=20, null=True), blank=True, null=True, size=8),
        ),
    ]
