# Generated by Django 3.2.4 on 2021-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0009_deal_processed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinterestrate',
            name='floor_rate',
            field=models.FloatField(default=1, help_text='Value must be in percentage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_processing_fee_extra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='free_partial_payment_per_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bank',
            name='max_bank_processing_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='down_payment',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='loan_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='property_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='governmentfee',
            name='mortgage_fee_addition',
            field=models.IntegerField(help_text='Land department property registration fixed fee in numbers'),
        ),
        migrations.AlterField(
            model_name='governmentfee',
            name='property_fee_addition',
            field=models.IntegerField(help_text='Land department property registration fixed fee in numbers'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='extra_financing',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='load_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
