# Generated by Django 3.2.4 on 2021-09-19 12:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0010_auto_20210915_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=2000)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('cc_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('bcc_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_processed_email', to='mortgage.deal')),
            ],
        ),
    ]
