# Generated by Django 3.2.4 on 2021-09-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0011_processemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinterestrate',
            name='floor_rate',
        ),
        migrations.RemoveField(
            model_name='eibor',
            name='eibor_rate',
        ),
        migrations.AddField(
            model_name='eibor',
            name='eibor_rate_1m',
            field=models.FloatField(default=0.0, help_text='Value must be in percentage', verbose_name='1M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eibor',
            name='eibor_rate_3m',
            field=models.FloatField(default=0.01, help_text='Value must be in percentage', verbose_name='3M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eibor',
            name='eibor_rate_6m',
            field=models.FloatField(default=0.2, help_text='Value must be in percentage', verbose_name='6M'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankinterestrate',
            name='eibor_duration',
            field=models.CharField(choices=[('1M', '1M'), ('3M', '3M'), ('6M', '6M')], max_length=2),
        ),
    ]
