# Generated by Django 3.2.4 on 2021-10-03 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mortgage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0012_auto_20210926_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='govt_fee',
            field=models.ForeignKey(default=mortgage.models.get_govt_fee, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deal_govt_fee', to='mortgage.governmentfee'),
        ),
        migrations.AddField(
            model_name='governmentfee',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 10, 4)),
            preserve_default=False,
        ),
    ]
