# Generated by Django 3.2.4 on 2021-11-02 21:49

from django.db import migrations, models
import django.db.models.deletion
import mortgage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0013_auto_20211004_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='EiborPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eibor_post_rate_0m', models.FloatField(default=0, help_text='Value must be in percentage', verbose_name='0M')),
                ('eibor_post_rate_1m', models.FloatField(help_text='Value must be in percentage', verbose_name='1M')),
                ('eibor_post_rate_3m', models.FloatField(help_text='Value must be in percentage', verbose_name='3M')),
                ('eibor_post_rate_6m', models.FloatField(help_text='Value must be in percentage', verbose_name='6M')),
            ],
            bases=(mortgage.models.SingleInstanceMixin, models.Model),
        ),
        migrations.AddField(
            model_name='bankinterestrate',
            name='eibor_post_duration',
            field=models.CharField(choices=[('0M', '0M'), ('1M', '1M'), ('3M', '3M'), ('6M', '6M')], default='0M', max_length=2),
        ),
        migrations.AddField(
            model_name='bankinterestrate',
            name='eibor_post_rate',
            field=models.FloatField(default=0, help_text='Value must be in percentage'),
        ),
        migrations.AddField(
            model_name='eibor',
            name='eibor_rate_0m',
            field=models.FloatField(default=0, help_text='Value must be in percentage', verbose_name='0M'),
        ),
        migrations.AlterField(
            model_name='bankinterestrate',
            name='eibor_duration',
            field=models.CharField(choices=[('0M', '0M'), ('1M', '1M'), ('3M', '3M'), ('6M', '6M')], default='0M', max_length=2),
        ),
        migrations.AlterField(
            model_name='governmentfee',
            name='real_state_fee',
            field=models.FloatField(help_text='Real estate fee in percentage excluding vat'),
        ),
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New Deal'), ('quote', 'Quote Sent'), ('preApproval', 'Pre Approval'), ('valuation', 'Valuation'), ('offer', 'Final Offer'), ('settlement', 'Settlement'), ('loanDisbursal', 'Loan Disbursal'), ('propertyTransfer', 'Property Transfer'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], max_length=50)),
                ('sub_stage', models.CharField(choices=[('Select Bank', 'select_bank'), ('Confirm Bank', 'confirm_bank'), ('Waiting for Pre Approval Documments', 'wait_preapproval_doc'), ('Sent to Bank for Approval', 'sent_to_bank_for_preapproval'), ('Waiting for Valuation Documents', 'waiting for valuation documents'), ('Sent to Bank for Approval', 'sent_to_bank_for_approval'), ('FOL Requested From Bank', 'for_request_from_bank'), ('FOL signed', 'fol_signed'), ('Settlement', 'settlement'), ('Property Transfer', 'property_transfer'), ('Payment', 'payment')], max_length=50)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_substages', to='mortgage.deal')),
            ],
            options={
                'unique_together': {('deal', 'stage', 'sub_stage')},
            },
        ),
    ]
