# Generated by Django 3.2.4 on 2021-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0014_auto_20211103_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_processing_fee_extra',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='max_bank_processing_fee',
        ),
        migrations.AddField(
            model_name='approval',
            name='name',
            field=models.CharField(choices=[('bank application form', 'bank application form'), ('salary certificate', 'salary certificate'), ('bank statement', 'bank statement'), ('payslips', 'payslips'), ('passport', 'passport'), ('visa', 'visa'), ('emirates id front', 'emirates id front'), ('emirates id back', 'emirates id back'), ('memorandum of understanding', 'memorandum of understanding'), ('property title deed', 'property title deed'), ('sellers passport', 'sellers passport'), ('sellers visa', 'sellers visa'), ('sellers emirates id back', 'sellers emirates id back'), ('sellers emirates id front', 'sellers emirates id front')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bank_reference_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='substage',
            name='sub_stage',
            field=models.CharField(choices=[('Select Bank', 'select bank'), ('Confirm Bank', 'confirm bank'), ('Waiting for Pre Approval Documments', 'wait preapproval doc'), ('Sent to Bank for Approval', 'sent to bank for preapproval'), ('Waiting for Valuation Documents', 'waiting for valuation documents'), ('Sent to Bank for Approval', 'sent to bank for approval'), ('FOL Requested From Bank', 'fol request from bank'), ('FOL signed', 'fol signed'), ('Settlement', 'settlement'), ('Property Transfer', 'property transfer'), ('Payment', 'payment')], max_length=50),
        ),
    ]
