# Generated by Django 3.2.4 on 2021-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0015_auto_20211109_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_processing_fee_extra',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='max_bank_processing_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
