# Generated by Django 3.2.4 on 2021-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0016_auto_20211110_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bank_processing_fee_extra',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='max_bank_processing_fee',
        ),
        migrations.AddField(
            model_name='bank',
            name='sample_form',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
